#!/usr/bin/env python3
"""Generate RATL_SPEC.md from src/ratl_def.tsv"""

import sys
from collections import OrderedDict

def load_def(path):
    symbols = []
    with open(path) as f:
        header = f.readline()
        for line in f:
            parts = line.rstrip('\n').split('\t')
            if len(parts) >= 6:
                src, r_code, n_in, n_out, desc, category = (
                    parts[0], parts[1], parts[2], parts[3], parts[4], parts[5]
                )
                symbols.append({
                    'src': src, 'r_code': r_code,
                    'n_in': int(n_in), 'n_out': int(n_out),
                    'desc': desc, 'category': category
                })
    return symbols

def categorize(symbols):
    cats = OrderedDict()
    for s in symbols:
        cat = s['category']
        if cat not in cats:
            cats[cat] = []
        cats[cat].append(s)
    return cats

def format_symbol(s, max_code_len=30):
    src = s['src'].replace('|', '\\|')
    r_code = s['r_code'].replace('|', '\\|')
    if len(r_code) > max_code_len:
        r_code = r_code[:max_code_len-1] + '…'
    desc = s['desc']
    n_in = s['n_in']
    n_out = s['n_out']
    return f"| `{src}` | `{r_code}` | {desc} | {n_in} → {n_out} |"

def hr():
    return "***"

def generate_spec(symbols):
    cats = categorize(symbols)

    lines = []
    lines.append("# RATL Specification")
    lines.append("")
    lines.append("RATL (R-based Array Manipulation Language) is a stack-based, esoteric programming language inspired by [MATL](https://github.com/lmendo/MATL). It leverages R's powerful statistical and matrix capabilities through a concise, postfix syntax, making it highly suitable for code golf.")
    lines.append("")
    lines.append(f"**Total symbols: {len(symbols)}** (all 2-byte or shorter)")
    lines.append("")
    lines.append("## 1. Introduction")
    lines.append("")
    lines.append("RATL is implemented in R and uses R's internal data structures (vectors, lists, matrices) to handle stack operations. It translates RATL code into R code, which is then evaluated.")
    lines.append("")
    lines.append("### 1.1 The Name")
    lines.append("The name stands for **R-based Array Manipulation Language**, reflecting its foundation in R and its primary focus on array-based operations.")
    lines.append("")
    lines.append("### 1.2 Notation")
    lines.append("- `$n`: Represents the $n$-th element popped from the stack (starting from the top).")
    lines.append("- `stack`: The global list used for storage.")
    lines.append("- `H, G, L, M`: Clipboards for temporary storage outside the stack.")
    lines.append("")
    lines.append(hr())
    lines.append("")
    lines.append("## 2. The Stack and Data Types")
    lines.append("")
    lines.append("RATL is a stack-based language where every operation interacts with a global stack (an R `list`).")
    lines.append("")
    lines.append("### Data Types")
    lines.append("RATL uses native R types:")
    lines.append("- **Numeric**: Integers and floating-point numbers (R `numeric`).")
    lines.append("- **Logical**: Boolean values (`TRUE`, `FALSE`).")
    lines.append("- **Character**: Strings of text (R `character`).")
    lines.append("- **List/Cell Array**: Collections of items, which can be of mixed types (R `list`).")
    lines.append("- **Matrix**: 2D arrays (R `matrix`).")
    lines.append("")
    lines.append(hr())
    lines.append("")
    lines.append("## 3. Statements and Separators")
    lines.append("")
    lines.append("- **Space**: Acts as a token separator.")
    lines.append("- **Newline**: Ignored by the parser but acts as a token separator.")
    lines.append("- **Comments**: Lines starting with `#` are treated as comments and ignored.")
    lines.append("")
    lines.append(hr())
    lines.append("")
    lines.append("## 4. Literals")
    lines.append("")
    lines.append("Literals are pushed onto the stack as soon as they are encountered.")
    lines.append("")
    lines.append("### 4.1 Numbers")
    lines.append("Standard numeric notation: `1`, `10`, `3.14`, `-5`.")
    lines.append("")
    lines.append("### 4.2 Numerical Arrays (Vectors)")
    lines.append("Enclosed in square brackets `[...]`. Elements are separated by spaces.")
    lines.append("Example: `[1 2 3]` pushes a numeric vector of length 3.")
    lines.append("")
    lines.append("### 4.3 Character Arrays (Strings)")
    lines.append("Enclosed in single quotes `'...'`.")
    lines.append("Example: `'hello'` pushes a character vector of length 1.")
    lines.append("")
    lines.append("### 4.4 Cell Arrays (Lists)")
    lines.append("Enclosed in curly braces `{...}`.")
    lines.append("Example: `{1 'a' [1 2]}` pushes an R list containing three different types.")
    lines.append("")
    lines.append(hr())
    lines.append("")
    lines.append("## 5. Control Flow")
    lines.append("")
    lines.append("RATL uses special symbols for conditional branching and loops.")
    lines.append("")
    lines.append("### 5.1 Conditional Branching (`? ... ]`)")
    lines.append("- **Symbols**: `?` starts the block, `]` ends it.")
    lines.append("- **If-Else**: `? truthy ; falsy ]`. The `;` separator distinguishes the \"then\" and \"else\" branches.")
    lines.append("- **Logic**: Pops the top element. If it's true, it executes the code until `]` (or `;`). If false and `;` is present, it executes the code between `;` and `]`.")
    lines.append("")
    lines.append("### 5.2 While/Repeat Loop (`\" ... \"`)")
    lines.append("- **Symbol**: `\"`")
    lines.append("- **Logic**: Starts a loop. At the end of the loop (marked by another `\"`), it pops the top element. If it's true, it repeats.")
    lines.append("")
    lines.append("### 5.3 For-Each Loop (`( ... )`)")
    lines.append("- **Symbols**: `(` and `)`")
    lines.append("- **Logic**: `(` pops an array/list. It then iterates through each element, pushing it onto the stack and executing the code between `(` and `)`.")
    lines.append("")
    lines.append("### 5.4 Infinite Loop (`` ` ... ` ``)")
    lines.append("- **Symbols**: `` ` `` starts and ends the loop.")
    lines.append("- **Logic**: Executes the code within the backticks repeatedly. Use the `X` (break) symbol to exit.")
    lines.append("")
    lines.append("### 5.5 Higher-Order Functions (Block Consumers)")
    lines.append("")
    lines.append("These functions pop a `{block}` from the stack and apply it to data.")
    lines.append("")
    lines.append("| Symbol | Name | Description |")
    lines.append("|--------|------|-------------|")
    lines.append("| `q` | Map | `{block} array q` — applies block to each element |")
    lines.append("| `e` | Filter | `{block} array e` — keeps elements where block returns truthy |")
    lines.append("| `y` | Reduce | `{block} array y` — fold left with block |")
    lines.append("| `z` | Repeat | `N {block} z` — executes block N times |")
    lines.append("| `@` | Execute | `{block} @` — pops and executes a block immediately |")
    lines.append("")
    lines.append(hr())
    lines.append("")
    lines.append("## 6. Implicit Actions")
    lines.append("")
    lines.append("### 6.1 Initial Actions")
    lines.append("- The stack is initialized as an empty `list()`.")
    lines.append("- A connection to `stdin` is opened for input operations.")
    lines.append("")
    lines.append("### 6.2 Final Actions")
    lines.append("- **Implicit Print**: If the stack contains exactly one element, it is printed automatically. If it contains more than one, the entire stack is printed as a list.")
    lines.append("- **Invisible Output**: The final evaluation result is returned invisibly in R.")
    lines.append("")
    lines.append(hr())
    lines.append("")
    lines.append("## 7. Meta-Programming")
    lines.append("")
    lines.append("RATL supports meta-programming — code that generates or manipulates other code at runtime.")
    lines.append("")
    lines.append("### 7.1 Dynamic Evaluation (`ev`)")
    lines.append("")
    lines.append("Pops a string from the stack and executes it as RATL code:")
    lines.append("")
    lines.append("```")
    lines.append("'3 5 +' ev        → 8")
    lines.append("'[1 2 3] s' ev    → 6")
    lines.append("'5 fp' ev         → 120")
    lines.append("```")
    lines.append("")
    lines.append("### 7.2 Dispatch List (`zD`)")
    lines.append("")
    lines.append("Pushes a list of all available symbol names onto the stack:")
    lines.append("")
    lines.append("```")
    lines.append("zD    → [+ - * / D w x ...]")
    lines.append("```")
    lines.append("")
    lines.append("### 7.3 Dynamic Dispatch (`zS`)")
    lines.append("")
    lines.append("Calls a symbol by name (string):")
    lines.append("")
    lines.append("```")
    lines.append("3 5 '+' zS    → 8")
    lines.append("5 'sq' zS     → 2.236...")
    lines.append("```")
    lines.append("")
    lines.append("### 7.4 Shell Exec (`zX`)")
    lines.append("")
    lines.append("Runs a shell command and pushes the output:")
    lines.append("")
    lines.append("```")
    lines.append("'echo hello' zX    → \"hello\"")
    lines.append("'ls' zX            → file listing")
    lines.append("```")
    lines.append("")
    lines.append("### 7.5 Sort By (`zB`)")
    lines.append("")
    lines.append("Sorts an array using a block as the key function:")
    lines.append("")
    lines.append("```")
    lines.append("[3 1 4 1 5] {0-} zB    → 1 1 3 4 5 (reverse sort)")
    lines.append("[1 2 3] {2 *} zB       → 1 2 3")
    lines.append("```")
    lines.append("")
    lines.append("### 7.6 Group By (`zG`)")
    lines.append("")
    lines.append("Groups array elements by the block's return value:")
    lines.append("")
    lines.append("```")
    lines.append("[1 2 3 4 5 6] {2 %} zG    → $0: [2 4 6] $1: [1 3 5]")
    lines.append("```")
    lines.append("")
    lines.append("### 7.7 Scan (`zC`)")
    lines.append("")
    lines.append("Like reduce, but returns all intermediate results:")
    lines.append("")
    lines.append("```")
    lines.append("[1 2 3 4 5] {+} zC    → 1 3 6 10 15")
    lines.append("[2 3 4] {*} zC        → 2 6 24")
    lines.append("```")
    lines.append("")
    lines.append("### 7.8 Take While (`zT`)")
    lines.append("")
    lines.append("Takes elements while the block returns truthy:")
    lines.append("")
    lines.append("```")
    lines.append("[1 2 3 4 5] {4 <} zT    → 1 2 3")
    lines.append("```")
    lines.append("")
    lines.append("### 7.9 Drop While (`zW`)")
    lines.append("")
    lines.append("Drops elements while the block returns truthy:")
    lines.append("")
    lines.append("```")
    lines.append("[1 2 3 4 5] {3 <} zW    → 3 4 5")
    lines.append("```")
    lines.append("")
    lines.append("### 7.10 Zip With (`zZ`)")
    lines.append("")
    lines.append("Applies a block pairwise to two arrays:")
    lines.append("")
    lines.append("```")
    lines.append("[1 2 3] [4 5 6] {+} zZ    → 5 7 9")
    lines.append("```")
    lines.append("")
    lines.append(hr())
    lines.append("")
    lines.append("## 8. Symbol Reference")
    lines.append("")

    for i, (cat, syms) in enumerate(cats.items(), 1):
        lines.append(f"### 8.{i} {cat}")
        lines.append("")
        lines.append("| Symbol | R Code | Description | Stack Effect |")
        lines.append("|--------|--------|-------------|--------------|")
        for s in sorted(syms, key=lambda x: x['src']):
            lines.append(format_symbol(s))
        lines.append("")

    return '\n'.join(lines)

if __name__ == '__main__':
    tsv_path = sys.argv[1] if len(sys.argv) > 1 else 'src/ratl_def.tsv'
    symbols = load_def(tsv_path)
    spec = generate_spec(symbols)
    print(spec)
