project:
  type: default

format:
  pdf:
    include-in-header:
      text: |
        \usepackage{longtable,booktabs,array}
        \let\oldlongtable\longtable
        \let\endoldlongtable\endlongtable
        \renewenvironment{longtable}{%
          \begin{center}%
          \footnotesize%
          \oldlongtable%
        }{%
          \endoldlongtable%
          \end{center}%
        }
    documentclass: scrartcl
    papersize: letter
    geometry:
      - margin=1in
